name: "JFrog CLI Github Example"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
    steps:
      - name: setup JFrog CLI
      #this step uses github cli action
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      - name: Checkout 
      #doing a checkout because we want to build our jfrog cli and start the life cycle agains test
        uses: actions/checkout@v1
      - name: Build
        run: |
            # Ping the server
            jfrog rt ping
            # Ping the server
            jfrog rt ping
